app/urls.py
from django.urls import path, re_path
from .views import home_view, news_view, news_detail_view, ourClients_view, about_view, login_view, signup_view, try_login
from .views import NewsCreateView, NewsUpdateView, NewsDeleteView
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import serve
from django.contrib.auth import views as auth_views

app_name = 'app'

urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(template_name='app/home.html'), name='logout'),

    path('try_login/', try_login, name="try_login"),
    path('login/', auth_views.LoginView.as_view(template_name='app/login.html'), name='login'),
    path('signup/', signup_view, name='signup'),

    path('home/', home_view, name="home"),
    path('clients/', ourClients_view, name="clients"),
    path('about/', about_view, name='about'),
    path('news/', news_view, name='news'),
    path('news_detail/<int:pk>/', news_detail_view, name='news_detail'),
    path('news/create/', NewsCreateView.as_view(), name='news_create'),
    path('news/<int:pk>/update/', NewsUpdateView.as_view(), name='news_update'),
    path('news/<int:pk>/delete/', NewsDeleteView.as_view(), name='news_delete'),

    re_path(r'^(?!static/|media/|news_images).*$', RedirectView.as_view(url='/home/'))

]

manga_holic_django/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
# models.py

from django.db import models
from django.contrib.auth.models import User

class Manga(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mangas = models.ManyToManyField(Manga)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=255)
    payment_info = models.CharField(max_length=255)

class PurchaseHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mangas = models.ManyToManyField(Manga)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    purchase_date = models.DateTimeField(auto_now_add=True)

class News(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    price = models.IntegerField()
    author = models.CharField(max_length=255, blank=True, null=True)
    image = models.ImageField(upload_to='news_images/', blank=True, null=True)

app/forms.py
from django import forms
from .models import News

class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        exclude = ['author']
        fields = ['title', 'content', 'price', 'image']

app/views.py
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth import authenticate, login as auth_login
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from .models import News
from .forms import NewsForm

def is_staff(user):
    return user.is_authenticated and user.is_staff

class NewsCreateView(CreateView):
    model = News
    template_name = 'app/news_create.html'
    form_class = NewsForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('app:news')


class NewsUpdateView(UpdateView):
    model = News
    template_name = 'app/news_form.html'
    form_class = NewsForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        # Pasa la instancia de la noticia actual al formulario
        kwargs['instance'] = self.object
        return kwargs

    def form_valid(self, form):
        form.instance.author = str(self.request.user)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('app:news')


class NewsDeleteView(DeleteView):
    model = News
    template_name = 'app/news_confirm_delete.html'
    success_url = reverse_lazy('app:news')

def home_view(request):
    latest_news = News.objects.all()[:5] 

    print("Latest News:", latest_news)

    context = {
        'latest_news': latest_news,
    }

    return render(request, 'app/home.html', context)

def ourClients_view(request):
    context = {
    }

    return render(request, 'app/ourClients.html', context)

def try_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            auth_login(request, user)
            return redirect('app:home')
        else:
            return render(request, 'app/login.html')

def login_view(request):
    return render(request, 'app/login.html')

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('app:home')
        else:
            print(form.errors) 
    else:
        form = UserCreationForm()

    context = {'form': form}
    return render(request, 'app/signup.html', context)

def about_view(request):
    context = {
    }

    return render(request, 'app/about.html', context)

def news_view(request):
    all_news = News.objects.all()

    paginator = Paginator(all_news, 8)
    page = request.GET.get('page')

    try:
        latest_news = paginator.page(page)
    except PageNotAnInteger:
        latest_news = paginator.page(1)
    except EmptyPage:
        latest_news = paginator.page(paginator.num_pages)

    context = {
        'latest_news': latest_news,
    }

    return render(request, 'app/news.html', context)

def news_detail_view(request, pk):
    news_item = get_object_or_404(News, pk=pk)
    return render(request, 'app/news_detail.html', {'news_item': news_item})

app/templates/app/about.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Acerca de Nosotros{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'styles/about.css' %}">
{% endblock %}

{% block content %}
    <section id="mision-vision" class="center-div">
        
        <br>
        <h2>Misión</h2>
        <p>Nuestra misión en Waku Tienda es proporcionar a los amantes del manga un espacio donde puedan acceder y comprar a una amplia variedad de mangas.</p>

        <h2>Visión</h2>
        <p>Queremos ser el destino preferido para aquellos que buscan descubrir nuevos mangas y disfrutar de sus series favoritas.</p>
    </section>

    <section id="objetivos-informacion" class="center-div">
        <h2>Objetivos de la Organización</h2>
        <ul>
            <li>Proporcionar gran acceso a mangas de alta calidad.</li>
            <li>Fomentar la interacción y participación de la comunidad de lectores.</li>
        </ul>

        <h2>Información Adicional</h2>
        <p>Esta es una plataforma en línea comprometida con el amor por el manga. Te deseamos una grata y agradable experiencia.</p>
    </section>
{% endblock content %}

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %} - WAKU⸸TIENDA</title>
  <link rel="icon" href="{% static 'image/favicon.ico' %}" type="image/x-icon">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'styles/global.css' %}">
  <link rel="stylesheet" href="{% static 'styles/buttonGoUp.css' %}">
  <link rel="stylesheet" href="{% static 'styles/hud.css' %}">

  <script src="{% static 'js/buttonGoUp.js' %}" defer></script>

  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>

  {% block extra_css %}{% endblock %}
</head>
<script>
    function setSideBarState() {
        var toggleSidebarButton = document.getElementById("toggleSidebarButton");
        var sidebar = document.getElementById("sidebar");
        sidebar.classList.toggle("sidebar-active");
        touch.classList.toggle("touch-active");
}
</script>
<body>
    <div id="sidebar">
        <ul class="navbar-nav">
            <br>
            <li id="item-index" class="nav-item">
                <a class="title navbar-brand white-text" href="{% url 'app:home' %}" target="_parent">WAKU⸸TIENDA</a>
            </li>
            <br>
            <li id="nav-item" class="nav-item">
                <a class="nav-link" href="{% url 'app:news' %}" target="_parent">Productos</a>
            </li>
            <li id="nav-item" class="nav-item">
                <a class="nav-link" href="{% url 'app:clients' %}" target="_parent">Proveedores</a>
            </li>
            <li id="nav-item" class="nav-item">
                <a class="nav-link" href="{% url 'app:about' %}" target="_parent">Acerca</a>
            </li>
        </ul>
    </div>
    
    <div id="body-content">
        <header>
            <button id="toggleSidebarButton" onclick="setSideBarState()">≡</button>

            {% if user.is_authenticated %}
                <div class="saludo">Hola, {{ user.username }}</div>
                <form method="post" action="{% url 'app:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="st-button">Cerrar sesión</button>
                </form>
            {% else %}
                <a class="white-text right-align" href="{% url 'app:login' %}">Ingresa</a>
            {% endif %}
        </header>

        <div id="content">
            {% block content %}{% endblock %}
        </div>

        <div id="touch" onclick="setSideBarState()"></div>
        <footer>
            <div class="row justify-content-end">
              <a onclick="scrollToTop()" class="col text-left text-white">Ir al Inicio</a>
        
              <p class="col text-right" style="margin-left: auto;">
                <a href="https://www.instagram.com/" target="_blank" class="col text-center">
                  <img src="{% static 'image/social/rrss_ig.webp' %}" alt="Instagram" width="20" height="20">
                </a>
          
                <a href="https://www.facebook.com/" target="_blank" class="col text-center">
                    <img src="{% static 'image/social/rrss_fb.png' %}" alt="Facebook" width="30" height="30">
                </a>
                Copyright 2024
              </p>
            </div>
        </footer>
    </div>
    
    <button id="scrollToTopButton" onclick="scrollToTop()" class="btn btn-danger rounded-circle btn-lg">
        <h2>↑</h2>
    </button>
</body>

</html>

app/templates/app/home.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block extra_css %}
  <link rel="stylesheet" href="{% static 'styles/carousel.css' %}">
{% endblock %}

{% block content %}

<div id="demo" class="carousel slide" data-ride="carousel">
  <ul class="carousel-indicators">
      {% for news_item in latest_news|slice:":5" %}
          <li data-target="#demo" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
      {% endfor %}
  </ul>
  <div class="carousel-inner">
      {% for news_item in latest_news|slice:":5" %}
          <div class="carousel-item {% if forloop.first %}active{% endif %}">
              <img src="{{ news_item.image.url }}" alt="{{ news_item.title }}" width="1100" height="500">
              <div class="carousel-caption">
                  <h3>{{ news_item.title }}</h3>
                  <p>{{ news_item.content|slice:":100" }}...</p>
              </div>
          </div>
      {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
      <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
      <span class="carousel-control-next-icon"></span>
  </a>
</div>

<div class="center-div">
  <section>
    <h2 class="center">Últimos mangas añadidos</h2>
    <ul>
      <li> <a href="#" class="text-white">Kentaro Miura: Berserk ベルセルク TOMO 3 </a></li>
      <li><a href="#" class="text-white">Takehiko Inoue: Vagabond バガボンド TOMO 1</a></li>
      <li><a href="#" class="text-white">Hiroya Oku: Gantz ガンツ MUCHOS TOMOS</a></li>
    </ul>
  </section>

  <section class="center-div">
    <h2 class="text-center">Manga de la Semana<br>Oyasumi Punpun</h2>

    <div class="manga-info">
      <img src="{% static 'image/weekManga/Oyasumi_ini.jpg' %}" alt="Oyasumi Punpun Inicio"
        class="manga-week img-fluid mx-auto d-block">
      <br>
      <p class="center">
        "Oyasumi Punpun" es una obra maestra del mangaka Inio Asano. La historia sigue la vida de Punpun
        Punyama, un joven con una representación de pájaro, mientras enfrenta los desafíos de la vida, el
        amor y la pérdida.
      </p>
    </div>

    <div class="manga-info">
      <p class="center">
        Con una narrativa única y a menudo desgarradora, "Oyasumi Punpun" explora temas profundos y oscuros
        de la condición humana. Asano crea una experiencia emotiva que deja una marca duradera en los
        lectores.
      </p>
      <br>
      <img src="{% static 'image/weekManga/oyasumi_end.webp' %}" alt="Oyasumi Punpun Final"
        class="manga-week img-fluid mx-auto d-block">
      <br>
    </div>
  </section>

</div>

{% endblock content %}

app/templates/app/login.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Login{% endblock %}

{% block extra_css %}
{% endblock %}

{% block content %}
    <div class="center-div full-height">
        <h2>Inicia Sesión</h2>
        <form method="post" action="{% url 'app:try_login' %}" class="center-div full-width">
            {% csrf_token %}
            <br>
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>

            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>
            <br>

            <button class="st-button" type="submit">Login</button>
            <br>
        </form>
    </div>
    <p class="center-div">¿No tienes una cuenta? <a href="{% url 'app:signup' %}">Regístrate aquí</a></p>
{% endblock content %}

app/templates/app/news.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}MANGAS{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'styles/news.css' %}">
{% endblock %}

{% block content %}

<div class="news-container-flexbox">
    <section class="center-div">
        <h1>Últimos Productos</h1>
        <ul class="news-list">
            {% for news_item in latest_news %}
                <li>
                    <a href="{% url 'app:news_detail' pk=news_item.pk %}">
                        <img src="{{ news_item.image.url }}" alt="{{ news_item.title }}" width="300" height="200">
                        <h5>{{ news_item.title }}</h5>
                        <br>
                        <h6>{{ news_item.content|slice:":100" }}</h6>
                        <br>
                        <h6>${{ news_item.price}}</h6>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </section>

    <div class="pagination center-div">
        <span class="step-links">
            {% if latest_news.has_previous %}
                <a href="?page=1">&laquo; Ir al Primero</a>
                <a href="?page={{ latest_news.previous_page_number }}">Anterior</a>
            {% endif %}
    
            {% for num in latest_news.paginator.page_range %}
                {% if num == latest_news.number %}
                    <span class="current">{{ num }}</span>
                {% else %}
                    <a href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}

            {% if user.is_staff %}
                <a href="{% url 'app:news_create' %}">Crear Nuevo Producto</a>
            {% endif %}
    
            {% if latest_news.has_next %}
                <a href="?page={{ latest_news.next_page_number }}"> Siguiente</a>
                <a href="?page={{ latest_news.paginator.num_pages }}">Ir al último &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>

{% endblock content %}

app/templates/app/news_confirm_delete.html
{% extends 'app/base.html' %}
{% block title %}Confirmar Eliminación{% endblock %}

{% block content %}
  <h1>¿Estás seguro de que deseas eliminar el manga "{{ news_item.title }}"?</h1>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Sí, eliminar</button>
  </form>
  <a href="{% url 'app:news' %}">Cancelar</a>
{% endblock %}

app/templates/app/news_create.html
{% extends 'app/base.html' %}
{% block title %}Crear Noticia{% endblock %}

{% block content %}
  <h1 class="center-div build-form">Crear Producto</h1>
  <form method="post" enctype="multipart/form-data" class="center-div build-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
  </form>
  <a href="{% url 'app:news' %}">Volver a la Lista de Productos</a>
{% endblock %}

app/templates/app/news_detail.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}{{ news_item.title }}{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'styles/news_detail.css' %}">
{% endblock %}

{% block content %}
    <div class="center-div">
        <br/>
        <h1 style="max-width: 80%;">{{ news_item.title }}</h1>
        <br/>
        <img src="{{ news_item.image.url }}" alt="{{ news_item.title }}" style="object-fit: cover;" width="80%" height="300">
        <br/>
        <p>{{ news_item.content|linebreaksbr }}</p>
        <br/>
        {% if user.is_staff %}
        <div class="horizontal-div">
            <form method="get" action="{% url 'app:news_update' pk=news_item.pk %}">
                <button type="submit" class="st-button">Editar</button>
            </form>
            <form method="post" action="{% url 'app:news_delete' pk=news_item.pk %}">
                {% csrf_token %}
                <button class="st-button" type="submit" onclick="return confirm('¿Estás seguro de que deseas eliminar esta noticia?')">Eliminar Noticia</button>
            </form>
        </div>
        {% endif %}
    </div>
{% endblock %}

app/templates/app/news_form.html
{% extends 'app/base.html' %}
{% block title %}{% if form.instance.pk %}Editar{% else %}Crear{% endif %} Noticia{% endblock %}

{% block content %}
  <h1 class="center-div">Editar Manga</h1>
  <form method="post" enctype="multipart/form-data" class="center-div build-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
  </form>
  <a href="{% url 'app:news' %}">Volver a la Lista de Mangas</a>
{% endblock %}

app/templates/app/ourClients.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Nuestros Proveedores{% endblock %}

{% block extra_css %}

{% endblock %}

{% block content %}
    <div class="center-div">
        <h2>Nuestros Proveedores</h2>
        <div class="center row">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Avatar</th>
                        <th>Name</th>
                        <th>Website</th>
                        <th>Editorial</th>
                    </tr>
                </thead>
                <tbody id="answerTable">
                </tbody>
            </table>
        </div>
    </div>

    <script src="{% static 'js/apiHandler.js' %}" defer></script>
{% endblock content %}

app/templates/app/signup.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Registro{% endblock %}

{% block extra_css %}
{% endblock %}

{% block content %}
    <div class="center-div full-height">
        <h2>Sé Parte de Nosotros</h2>
        <form method="post" action="{% url 'app:signup' %}">
            {% csrf_token %}
            <br>
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>

            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>

            <label for="password1">Password</label>
            <input type="password" id="password1" name="password1" pattern=".{10,}" required title="La contraseña debe tener al menos 10 caracteres y usar numeros y letras">

            <label for="password2">Confirmar Password:</label>
            <input type="password" id="password2" name="password2" pattern=".{10,}" required title="La contraseña debe tener al menos 10 caracteres y usar numeros y letras">
            <br>
            <br>
            <button class="st-button" type="submit">Registrar</button>
        </form>
    </div>
    <p class="center-div">¿Ya tienes una cuenta? <a href="{% url 'app:login' %}">Inicia sesión aquí</a></p>
{% endblock content %}